<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-SchoolRegister.Web-3992d3f5-1374-430e-81f7-f28038c54396</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.16" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.16" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.16" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SchoolRegister.Model\SchoolRegister.Model.csproj" />
    <ProjectReference Include="..\SchoolRegister.DAL\SchoolRegister.DAL.csproj" />
    <ProjectReference Include="..\SchoolRegister.ViewModels\SchoolRegister.ViewModels.csproj" />
    <ProjectReference Include="..\SchoolRegister.Services\SchoolRegister.Services.csproj" />
  </ItemGroup>

</Project>
